addSbtPlugin("com.eed3si9n"                         % "sbt-assembly"        % "0.14.6")
addSbtPlugin("com.github.sbt"                       % "sbt-native-packager" % "1.9.16")
addSbtPlugin("org.scalameta"                        % "sbt-native-image"    % "0.3.4")
addSbtPlugin("ch.epfl.scala"                        % "sbt-scalafix"        % "0.11.1")
addSbtPlugin("org.scalameta"                        % "sbt-scalafmt"        % "2.5.2")
