name: GraalVM build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build contextus native image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-12 ]
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-12
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: 21
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm' # GraalVM version
          java-version: '21'
          components: 'native-image'
      - name: Build and package
        run: sbt packageCli
      - name: Rename artifact
        run: for f in *.zip; do mv $f $(printf '%s\n' "${f%.zip}-${{ matrix.arch }}.zip"); done
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: contextus-*.zip
