name: Test Project
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test application
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: 21
      - name: Automated tests
        run: sbt test
